name: build temurin images
on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - main
    paths:
      - temurin/**
permissions:
  actions: read
  packages: write
concurrency:
  group: temurin-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  push:
    name: "temurin_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 17
          - 21
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./temurin
          platforms: linux/amd64, linux/arm64
          file: ./temurin/${{ matrix.tag }}/Dockerfile
          push: true
          tags: ghcr.io/minestarua/pterodactyl-images:temurin_${{ matrix.tag }}
